FROM php:8.0

USER root

ENV DEBIAN_FRONTEND noninteractive
ENV PHP_ENABLE_XDEBUG 1
ENV PATH /root/.composer/vendor/bin:$PATH
ENV PATH /opt/code/vendor/bin:$PATH

RUN apt-get clean && apt-get dist-upgrade \
	&& apt-get update -y --allow-insecure-repositories
 
RUN apt-get install -y --allow-unauthenticated \
	libmagickwand-dev \
	libmagickcore-dev \
	libwebp-dev \
	libjpeg62-turbo-dev \
	libpng-dev libxpm-dev \
	libfreetype6-dev \
	libzip-dev zip unzip \
	libz-dev \
	libmemcached-dev memcached \
	libxslt-dev \
	zlib1g-dev \
	libssl-dev \
	librdkafka-dev \
	mc iputils-ping curl \
	ca-certificates wget nano git \
	libmcrypt-dev \
	libsqlite3-dev \
	libxml2-dev \
	libcurl3-dev \
	libedit-dev \
	libpspell-dev \
	libldap2-dev \
	unixodbc-dev \
	libpq-dev 

RUN PHP_OPENSSL=yes \
	&& PHP_ENABLE_XDEBUG=1 \
	&& ln -fs /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/ \
	&& pecl install memcached msgpack xdebug \
	&& docker-php-ext-enable memcached msgpack xdebug \
	&& pecl bundle -d /usr/src/php/ext/ igbinary \
	&& docker-php-ext-configure gd \
	--with-webp --with-jpeg --with-freetype \
	&& docker-php-ext-install exif xml filter zip bcmath gd intl mysqli \
	pdo_mysql gettext pcntl sysvmsg sysvsem sysvshm xsl calendar ffi shmop \
	sockets opcache igbinary 

RUN echo "xdebug.mode=coverage" > /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& echo "xdebug.client_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini \
	&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
